version: '3.8'

services:
  spark-master:
    image: bitnami/spark:3.4.1
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_EXTRA_CLASSPATH=/opt/spark/jars/*
      - SPARK_EXTRA_CLASSPATH=/opt/spark/jars/*
      - SPARK_SUBMIT_OPTIONS=--jars /opt/spark/jars/...
      - SPARK_SQL_EXTENSIONS=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
      - SPARK_SQL_CATALOG_SPARK_CATALOG=org.apache.iceberg.spark.SparkSessionCatalog
      - SPARK_SQL_CATALOG_SPARK_CATALOG_TYPE=hive
    ports:
      - "8081:8080"
      - "7077:7077"
      - "4040:4040"
    volumes:
      - spark-logs:/opt/spark/logs
      - ../processing/jars:/opt/spark/jars:ro
      - iceberg-warehouse:/opt/iceberg/warehouse
    networks:
      - 24sender-network

  spark-worker:
    image: bitnami/spark:3.4.1
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_EXTRA_CLASSPATH=/opt/spark/jars/*
      - SPARK_SUBMIT_OPTIONS=--jars /opt/spark/jars/...
      - SPARK_SQL_EXTENSIONS=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
      - SPARK_SQL_CATALOG_SPARK_CATALOG=org.apache.iceberg.spark.SparkSessionCatalog
      - SPARK_SQL_CATALOG_SPARK_CATALOG_TYPE=hive
    volumes:
      - ../processing/jars:/opt/spark/jars
    networks:
      - 24sender-network

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - 24sender-network

  minio-init:
    image: minio/mc:latest
    container_name: minio-init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set myminio http://minio:9000 minioadmin minioadmin;
      mc mb myminio/bronze || true;
      mc mb myminio/silver || true;
      mc mb myminio/gold || true;
      mc mb myminio/iceberg-warehouse || true;
      exit 0;
      "
    networks:
      - 24sender-network

  spark-submit:
    image: bitnami/spark:3.4.1
    container_name: spark-submit
    depends_on:
      - spark-master
      - minio-init
    environment:
      - SPARK_MODE=client
      - SPARK_EXTRA_CLASSPATH=/opt/spark/jars/*
      - SPARK_SUBMIT_OPTIONS=--jars /opt/spark/jars/spark-sql-kafka-0-10_2.12-3.4.1.jar,/opt/spark/jars/kafka-clients-3.4.0.jar,/opt/spark/jars/lz4-java-1.8.0.jar,/opt/spark/jars/iceberg-spark-runtime-3.4_2.12-1.4.2.jar \
        --conf spark.sql.catalog.spark_catalog=org.apache.iceberg.spark.SparkSessionCatalog \
        --conf spark.sql.catalog.spark_catalog.type=hive \
        --conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
    volumes:
      - ../processing/jobs:/opt/jobs
      - ../processing/data:/opt/spark-apps/data:ro
      - ../processing/jars:/opt/spark/jars
    networks:
      - 24sender-network
    command: sleep infinity

volumes:
  minio-data:
  spark-logs:
  iceberg-warehouse:

networks:
  24sender-network:
    external: true
    name: 24sender-network 