version: "3.9"

services:
  24sender-zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: 24sender-zookeeper
    hostname: zookeeper
    ports: ["2181:2181"]
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks: [data_eng_net]

  24sender-kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: 24sender-kafka
    hostname: kafka
    depends_on: [24sender-zookeeper]
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks: [data_eng_net]

  24sender-kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: 24sender-kafka-ui
    depends_on: [24sender-kafka]
    ports: ["8090:8080"]
    environment:
      KAFKA_CLUSTERS_0_NAME: 24sender
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks: [data_eng_net]

  csv-producer:
    build: .
    depends_on: [24sender-kafka]
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      PYTHONUNBUFFERED: "1"
      KAFKA_TOPIC: email_send_stream
      CSV_FILE: /data/bronze/bronze_email_send_stream.csv
      THROTTLE_MS: 200
    volumes:
      - ../data/bronze:/data/bronze
    networks: [data_eng_net]

networks:
  data_eng_net:
    external: true
