version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - 24sender-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-broker
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - 24sender-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - 24sender-network

  kafka-producer:
    build: ./producers
    container_name: kafka-producer
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      PYTHONUNBUFFERED: 1
    networks:
      - 24sender-network
    restart: unless-stopped
  
  email-send-producer:
    build: ./producers
    container_name: kafka-producer-email
    command: >
      bash -c "
        pip install --no-cache-dir kafka-python &&
        test -r /app/data/bronze_email_send_stream.csv &&
        python -u publish_email_send.py /app/data/bronze_email_send_stream.csv 0.2 0.8
      "
    volumes:
      - ../processing/jobs/data/bronze/bronze_email_send_stream.csv:/app/data/bronze_email_send_stream.csv:ro
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - KAFKA_TOPIC=email_send_stream
      - PYTHONUNBUFFERED=1
    depends_on:
      - kafka
    networks:
      - 24sender-network
    restart: unless-stopped

networks:
  24sender-network:
    external: true
    name: 24sender-network 
